[book]
title = "Мерцание. Книга Кая"
authors = ["bestdeejay-design"]
description = "Научно-философская сага о вечности сознания, циклах времени и силе мечты."
src = "files"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"

[output.html.playground]
runnable = false

[output.epub]
optional = true
