[book]
title = "Мерцание"
authors = ["bestdeejay-design"]
description = "Научно-философская сага о вечности сознания, циклах времени и силе мечты."
src = "files"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
no-section-label = true
additional-css = ["custom/custom.css"]
additional-js = ["custom/custom.js"]
favicon = "favicon.svg"

[output.html.playground]
runnable = false

[output.epub]
optional = true
